(() => {
  const app = window.__vettaApp;
  const root = document.getElementById('view-planning');
  if (!app || !root || root.dataset.block1a === 'ready') return;
  root.dataset.block1a = 'ready';
  root.innerHTML = `
    <div class="rounded-[2rem] bg-vetta-900 p-8 text-white">
      <button data-back class="mb-6 -ml-2 px-2 py-1 text-xs font-extrabold text-blue-200"><i class="fas fa-arrow-left mr-2"></i>Voltar</button>
      <span class="text-[10px] text-blue-300 font-extrabold uppercase tracking-widest">Planejamento</span>
      <h2 class="text-2xl font-extrabold mt-2">Meu planejamento completo</h2>
      <p class="text-sm text-slate-400 mt-2">Meta, agenda, operação, custos e distribuição no mesmo lugar.</p>
    </div>
    <div class="card-vetta p-6">
      <div class="flex justify-between items-start gap-3"><div><span class="label-micro !text-vetta-900">Resumo do plano</span><h3 class="font-extrabold text-lg">O que seu mês precisa</h3></div><span class="px-3 py-1.5 rounded-full bg-blue-50 text-blue-600 text-[10px] font-extrabold">BLOCO 1A</span></div>
      <div class="grid grid-cols-2 gap-3 mt-5">
        <div class="bg-emerald-50 rounded-2xl p-4"><span class="label-micro !text-emerald-700">Objetivo líquido</span><strong id="planningTarget" class="text-lg text-emerald-600 tabular">R$ 0</strong></div>
        <div class="bg-blue-50 rounded-2xl p-4"><span class="label-micro !text-blue-700">Faturamento por dia</span><strong id="planningDailyGross" class="text-lg text-blue-600 tabular">R$ 0</strong></div>
        <div class="bg-slate-50 rounded-2xl p-4"><span class="label-micro">Dias planejados</span><strong id="planningDays" class="text-lg">0 dias</strong></div>
        <div class="bg-slate-50 rounded-2xl p-4"><span class="label-micro">Rodagem por dia</span><strong id="planningDailyKm" class="text-lg">0 km</strong></div>
      </div><p id="planningSummaryText" class="text-xs text-slate-500 mt-4 leading-relaxed"></p>
    </div>
    <details class="card-vetta overflow-hidden" open><summary class="details-summary"><div><span class="label-micro !mb-0 !text-vetta-900">Metas</span><strong>Objetivo mensal</strong></div><i class="fas fa-chevron-down"></i></summary><div class="p-6 pt-0 space-y-4"><div><label class="label-micro">Meta líquida mensal</label><div class="input-wrapper"><span>R$</span><input id="planningTargetInput" type="number" min="0" step="100" class="input-vetta"></div></div><p class="text-xs text-slate-500">Usa a mesma meta de Início e Ajustes.</p></div></details>
    <details class="card-vetta overflow-hidden" open><summary class="details-summary"><div><span class="label-micro !mb-0 !text-vetta-900">Agenda</span><strong>Dias de trabalho e folgas</strong></div><i class="fas fa-chevron-down"></i></summary><div class="p-6 pt-0 space-y-5">
      <div class="bg-slate-50 p-1.5 rounded-2xl flex gap-1"><button data-plan-days="5" class="plan-day flex-1 py-3 rounded-xl text-[10px] font-bold uppercase">5 dias</button><button data-plan-days="6" class="plan-day flex-1 py-3 rounded-xl text-[10px] font-bold uppercase">6 dias</button><button data-plan-days="7" class="plan-day flex-1 py-3 rounded-xl text-[10px] font-bold uppercase">7 dias</button></div>
      <div><span class="label-micro">Dias específicos</span><div class="grid grid-cols-7 gap-1.5 mt-3"><button data-plan-weekday="1" class="plan-weekday py-3 rounded-xl text-[10px] font-bold">SEG</button><button data-plan-weekday="2" class="plan-weekday py-3 rounded-xl text-[10px] font-bold">TER</button><button data-plan-weekday="3" class="plan-weekday py-3 rounded-xl text-[10px] font-bold">QUA</button><button data-plan-weekday="4" class="plan-weekday py-3 rounded-xl text-[10px] font-bold">QUI</button><button data-plan-weekday="5" class="plan-weekday py-3 rounded-xl text-[10px] font-bold">SEX</button><button data-plan-weekday="6" class="plan-weekday py-3 rounded-xl text-[10px] font-bold">SÁB</button><button data-plan-weekday="0" class="plan-weekday py-3 rounded-xl text-[10px] font-bold">DOM</button></div></div>
      <div><label class="label-micro">Folgas extras neste mês</label><input id="planningDaysOffInput" type="number" min="0" max="20" class="input-vetta no-mask"></div><p id="planningCalendarSummary" class="text-xs text-slate-500"></p>
    </div></details>
    <details class="card-vetta overflow-hidden"><summary class="details-summary"><div><span class="label-micro !mb-0 !text-vetta-900">Operação e combustível</span><strong id="planningFuelSummary">Combustível das metas</strong></div><i class="fas fa-chevron-down"></i></summary><div class="p-6 pt-0 space-y-5">
      <div class="grid grid-cols-2 gap-3"><div class="bg-amber-50 rounded-2xl p-4"><span class="label-micro !text-amber-700">Combustível/km</span><strong id="planningFuelCostKm" class="text-amber-600">R$ 0</strong></div><div class="bg-blue-50 rounded-2xl p-4"><span class="label-micro !text-blue-700">Receita média/km</span><strong id="planningRevenueSummary" class="text-blue-600">R$ 0</strong></div></div>
      <div><label class="label-micro">Tipo de combustível</label><select id="planningFuelType" class="input-vetta"><option value="gnv">GNV</option><option value="gasoline">Gasolina</option><option value="ethanol">Etanol</option><option value="diesel">Diesel</option><option value="custom">Personalizado</option></select></div>
      <div id="planningFuelLabelWrap" class="hidden"><label class="label-micro">Nome do combustível</label><input id="planningFuelLabel" class="input-vetta no-mask" maxlength="30"></div>
      <div class="grid grid-cols-2 gap-3"><div><label class="label-micro">Preço por unidade</label><div class="input-wrapper"><span>R$</span><input id="planningFuelPrice" type="number" step=".01" class="input-vetta"></div></div><div><label class="label-micro">Rendimento</label><input id="planningFuelEfficiency" type="number" step=".1" class="input-vetta no-mask"></div></div>
      <div><label class="label-micro">Receita média por km</label><div class="input-wrapper"><span>R$</span><input id="planningRevenueKm" type="number" step=".01" class="input-vetta"></div></div>
    </div></details>
    <details class="card-vetta overflow-hidden" open><summary class="details-summary"><div><span class="label-micro !mb-0 !text-vetta-900">Custos e reservas</span><strong>Para onde o dinheiro precisa ir</strong></div><i class="fas fa-chevron-down"></i></summary><div class="p-6 pt-0"><div class="flex justify-end"><button id="planningAddCostButton" class="px-4 py-3 rounded-2xl bg-blue-600 text-white text-xs font-extrabold"><i class="fas fa-plus mr-2"></i>Adicionar custo</button></div><div id="planningCostSummary" class="grid grid-cols-2 gap-3 mt-5"></div><div id="planningCostList" class="space-y-3 mt-5"></div></div></details>
    <div class="card-vetta overflow-hidden"><div class="p-6 border-b border-slate-50 bg-blue-50/50 flex justify-between"><div><span class="label-micro !mb-0 !text-vetta-900">Distribuição da meta</span><strong class="block text-sm mt-1">Como o faturamento será dividido</strong></div><i class="fas fa-chart-pie text-blue-500"></i></div><div class="p-6"><div class="chart-container mb-6"><canvas id="planningRevenueChart"></canvas></div>
      <div class="flex justify-between py-2 border-b border-dashed border-slate-100"><span class="text-sm font-bold">Faturamento bruto necessário</span><span id="planningDreGross" class="font-bold text-blue-600 tabular">R$ 0</span></div><div class="flex justify-between py-2 text-xs text-slate-500"><span>Rodagem mensal estimada</span><strong id="planningDreKm">0 km</strong></div>
      <div class="space-y-1 mb-4"><div class="flex justify-between text-xs text-red-500 bg-red-50/50 p-2 rounded-lg"><span>Combustível</span><strong id="planningDreFuel">R$ 0</strong></div><div class="flex justify-between text-xs text-orange-500 bg-orange-50/50 p-2 rounded-lg"><span>Custos por km</span><strong id="planningDreVariable">R$ 0</strong></div><div class="flex justify-between text-xs text-purple-500 bg-purple-50/50 p-2 rounded-lg"><span>Taxas percentuais</span><strong id="planningDrePercent">R$ 0</strong></div><div class="flex justify-between text-xs text-blue-500 bg-blue-50/50 p-2 rounded-lg"><span>Obrigações e reservas</span><strong id="planningDreFixed">R$ 0</strong></div></div><div class="flex justify-between items-center bg-emerald-50 p-3 rounded-xl"><span class="text-xs font-bold text-emerald-700 uppercase">Objetivo líquido</span><span id="planningDreNet" class="text-xl font-black text-emerald-600 tabular">R$ 0</span></div>
    </div></div>
    <div class="card-vetta p-6 bg-gradient-to-br from-purple-50 to-white"><span class="label-micro !text-purple-700">Aprendizado local</span><h3 class="font-extrabold text-lg">O VETTA aprende com seus registros</h3><p id="planningLearningText" class="text-xs text-slate-500 mt-2"></p><div id="planningLearningActions" class="space-y-3 mt-4"></div></div>
    <details class="card-vetta overflow-hidden"><summary class="details-summary"><div><span class="label-micro !mb-0 !text-red-600">Opções avançadas</span><strong>Restaurar parâmetros</strong></div><i class="fas fa-chevron-down"></i></summary><div class="p-6 pt-0"><p class="text-xs text-slate-500 mb-4">Preserva histórico e radar, mas restaura os parâmetros padrão.</p><button id="planningResetButton" class="w-full py-4 rounded-2xl bg-red-50 text-red-600 text-sm font-bold">Restaurar valores padrão</button></div></details>
    <div class="rounded-2xl bg-blue-50 p-4 text-xs text-blue-700 leading-relaxed"><strong>Transição segura:</strong> Início e Ajustes continuam completos durante o Bloco 1A. Nada foi retirado deles.</div>`;

  const $ = id => document.getElementById(id);
  let chart = null;
  const setInput = (id, value) => { const el = $(id); if (el && document.activeElement !== el) el.value = value; };
  const costHtml = cost => `<article class="cost-row ${cost.active ? '' : 'opacity-50'}"><div class="flex justify-between gap-3"><div><div class="flex items-center gap-2"><strong>${app.escape(cost.name)}</strong><span class="cost-kind">${app.costKindLabel(cost.kind)}</span></div><span class="text-xs text-slate-500">${cost.category === 'reserve' ? 'Reserva/objetivo' : 'Conta/obrigação'} · ${app.costValueText(cost)}</span></div><button data-cost-action="toggle" data-cost-id="${cost.id}" class="toggle ${cost.active ? 'active' : ''}" aria-label="Ativar ou desativar"></button></div><div class="flex justify-end gap-2 mt-3 pt-3 border-t border-slate-50"><button data-cost-action="edit" data-cost-id="${cost.id}" class="px-3 py-2 rounded-xl bg-blue-50 text-blue-600 text-[10px] font-extrabold">EDITAR</button><button data-cost-action="delete" data-cost-id="${cost.id}" class="px-3 py-2 rounded-xl bg-red-50 text-red-500 text-[10px] font-extrabold">EXCLUIR</button></div></article>`;
  const renderLearning = () => {
    const s = app.learningSuggestions(), items = [];
    if (s.revenue) items.push(`<div class="bg-white p-4 rounded-2xl"><p class="text-xs text-slate-600">Sua média real foi <strong>${app.money(s.revenue)}/km</strong>.</p><button data-learning="revenue" data-value="${s.revenue}" class="mt-3 text-[10px] font-extrabold text-purple-600">ATUALIZAR RECEITA MÉDIA</button></div>`);
    if (s.efficiency) items.push(`<div class="bg-white p-4 rounded-2xl"><p class="text-xs text-slate-600">Rendimento estimado: <strong>${s.efficiency.toFixed(1)} km/${app.state.fuel.unit}</strong>.</p><button data-learning="efficiency" data-value="${s.efficiency}" class="mt-3 text-[10px] font-extrabold text-purple-600">ATUALIZAR RENDIMENTO</button></div>`);
    $('planningLearningText').textContent = s.recent.length < 3 ? `Registre mais ${3 - s.recent.length} dia(s) para receber a primeira leitura.` : items.length ? 'Há sugestões baseadas nos seus próprios dias. Nada muda sem confirmação.' : 'Seus parâmetros estão coerentes com os registros recentes.';
    $('planningLearningActions').innerHTML = items.join('');
  };
  const renderChart = c => {
    if (root.classList.contains('hidden') || typeof Chart === 'undefined') return;
    chart?.destroy();
    chart = new Chart($('planningRevenueChart'), { type: 'doughnut', data: { labels: ['Líquido','Combustível','Por km','Taxas percentuais','Contas/Reservas'], datasets: [{ data: [app.state.targetProfit,c.totalFuel,c.totalVariable,c.totalPercent,c.costs.monthlyFixed], backgroundColor: ['#10B981','#EF4444','#F59E0B','#A855F7','#2563EB'], borderWidth: 0, hoverOffset: 4 }] }, options: { responsive: true, maintainAspectRatio: false, cutout: '72%', plugins: { legend: { position: 'bottom', labels: { usePointStyle: true, boxWidth: 8, padding: 16, font: { size: 10, weight: '700' } } }, tooltip: { callbacks: { label: x => ` ${x.label}: ${app.money(x.raw)}` } } } } });
  };
  const render = () => {
    const c = app.calculations(), ctx = c.ctx, f = app.state.fuel;
    $('planningTarget').textContent = app.money(app.state.targetProfit,0); $('planningDailyGross').textContent = app.money(c.dailyGross,0); $('planningDays').textContent = `${ctx.plannedDays} dias`; $('planningDailyKm').textContent = `${app.integer(c.dailyKm)} km`;
    $('planningSummaryText').textContent = `Com ${ctx.plannedDays} dias planejados e ${app.state.extraDaysOff} folga(s) extra(s), o plano estima ${app.money(c.totalGross,0)} de faturamento bruto no mês.`;
    setInput('planningTargetInput',app.state.targetProfit); setInput('planningDaysOffInput',app.state.extraDaysOff); setInput('planningRevenueKm',app.state.revenueKm); setInput('planningFuelType',f.type); setInput('planningFuelLabel',f.label); setInput('planningFuelPrice',f.price); setInput('planningFuelEfficiency',f.efficiency);
    $('planningFuelLabelWrap').classList.toggle('hidden',f.type !== 'custom'); $('planningCalendarSummary').textContent = `Há ${ctx.selectedDates.length} dias compatíveis com sua agenda. O plano considera ${ctx.plannedDays} dias de trabalho.`;
    document.querySelectorAll('.plan-day').forEach(b => b.className = `plan-day flex-1 py-3 rounded-xl text-[10px] font-bold uppercase ${Number(b.dataset.planDays) === app.currentDaysPerWeek() ? 'day-btn-active' : 'day-btn-inactive'}`);
    document.querySelectorAll('.plan-weekday').forEach(b => b.className = `plan-weekday py-3 rounded-xl text-[10px] font-bold ${app.state.workWeekdays.includes(Number(b.dataset.planWeekday)) ? 'weekday-active' : 'weekday-inactive bg-slate-50'}`);
    $('planningFuelSummary').textContent = `${f.label} · ${app.money(c.fuelKm)}/km`; $('planningFuelCostKm').textContent = `${app.money(c.fuelKm)}/km`; $('planningRevenueSummary').textContent = `${app.money(app.state.revenueKm)}/km`;
    $('planningCostSummary').innerHTML = `<div class="bg-red-50 rounded-2xl p-4"><span class="label-micro !text-red-700">Contas/mês</span><strong class="text-red-600">${app.money(c.costs.obligations)}</strong></div><div class="bg-emerald-50 rounded-2xl p-4"><span class="label-micro !text-emerald-700">Reservas/mês</span><strong class="text-emerald-600">${app.money(c.costs.reserves)}</strong></div><div class="bg-amber-50 rounded-2xl p-4"><span class="label-micro !text-amber-700">Custos por km</span><strong class="text-amber-600">${app.money(c.costs.perKm)}</strong></div><div class="bg-blue-50 rounded-2xl p-4"><span class="label-micro !text-blue-700">Itens ativos</span><strong class="text-blue-600">${c.costs.active.length}</strong></div>`;
    $('planningCostList').innerHTML = app.state.costs.length ? app.state.costs.map(costHtml).join('') : '<p class="text-sm text-slate-400 text-center py-5">Nenhum custo cadastrado.</p>';
    $('planningDreGross').textContent = app.money(c.totalGross); $('planningDreKm').textContent = `${app.integer(c.totalRequiredKm)} km`; $('planningDreFuel').textContent = `- ${app.money(c.totalFuel)}`; $('planningDreVariable').textContent = `- ${app.money(c.totalVariable)}`; $('planningDrePercent').textContent = `- ${app.money(c.totalPercent)}`; $('planningDreFixed').textContent = `- ${app.money(c.costs.monthlyFixed)}`; $('planningDreNet').textContent = app.money(app.state.targetProfit);
    renderLearning(); renderChart(c);
  };
  const save = () => { app.save(); app.syncInputs(); app.render(); };
  root.querySelector('[data-back]').addEventListener('click',() => app.navigateBack());
  $('planningTargetInput').addEventListener('change',e => { app.state.targetProfit = Math.max(0,app.number(e.target.value)); save(); });
  document.querySelectorAll('[data-plan-days]').forEach(b => b.addEventListener('click',() => { app.state.workWeekdays = app.weekdaysForCount(Number(b.dataset.planDays)); save(); }));
  document.querySelectorAll('[data-plan-weekday]').forEach(b => b.addEventListener('click',() => { const d = Number(b.dataset.planWeekday), s = new Set(app.state.workWeekdays); if (s.has(d)) { if (s.size === 1) return app.toast('Escolha pelo menos um dia de trabalho.'); s.delete(d); } else s.add(d); app.state.workWeekdays = [...s].sort((a,b) => a-b); save(); }));
  $('planningDaysOffInput').addEventListener('change',e => { app.state.extraDaysOff = app.clamp(Math.round(app.number(e.target.value)),0,20); save(); });
  $('planningFuelType').addEventListener('change',e => app.changeFuelType(e.target.value));
  $('planningFuelLabel').addEventListener('change',e => { app.state.fuel.label = e.target.value.trim() || 'Personalizado'; save(); });
  $('planningFuelPrice').addEventListener('change',e => { app.state.fuel.price = Math.max(0,app.number(e.target.value)); save(); });
  $('planningFuelEfficiency').addEventListener('change',e => { app.state.fuel.efficiency = Math.max(.1,app.number(e.target.value)); save(); });
  $('planningRevenueKm').addEventListener('change',e => { app.state.revenueKm = Math.max(.01,app.number(e.target.value)); save(); });
  $('planningAddCostButton').addEventListener('click',() => app.openCostModal()); $('planningCostList').addEventListener('click',e => app.handleCostAction(e)); $('planningLearningActions').addEventListener('click',e => app.handleLearningAction(e)); $('planningResetButton').addEventListener('click',() => app.reset());
  const baseRender = app.render; app.render = function() { baseRender.call(this); render(); }; app.renderPlanning = render; render();
})();
