import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';

const shell=readFileSync('app-shell.html','utf8'),main=readFileSync('ui/main.js','utf8'),modelSource=readFileSync('ui/model.js','utf8'),store=readFileSync('ui/store.js','utf8'),css=readFileSync('ui/premium.css','utf8'),friendlyCss=readFileSync('ui/friendly.css','utf8'),interaction=readFileSync('ui/interaction.js','utf8'),sw=readFileSync('sw.js','utf8');
const manifest=JSON.parse(readFileSync('manifest.webmanifest','utf8'));
const dashboard=readFileSync('ui/screens/dashboard.js','utf8'),planning=readFileSync('ui/screens/planning.js','utf8'),record=readFileSync('ui/screens/record.js','utf8'),results=readFileSync('ui/screens/results.js','utf8'),more=readFileSync('ui/screens/more.js','utf8'),onboarding=readFileSync('ui/screens/onboarding.js','utf8');

assert.ok(shell.includes('./ui/main.js'));assert.ok(shell.includes('./ui/premium.css'));assert.ok(shell.includes('./ui/interaction.js'));assert.ok(shell.includes('./ui/friendly.css'));
for(const legacy of ['app.js','refactor-360.js','planning-1a.js','today-1c.js','record-2.js'])assert.ok(!shell.includes(legacy),`shell ativo não pode carregar ${legacy}`);
assert.ok(!shell.includes('tailwindcss.com'));assert.ok(!shell.includes('chart.js'));
assert.match(main,/document\.body\.dataset\.uiAuthority\s*=\s*'premium-v1'/);assert.ok(main.includes('setRenderCallback(render)'));assert.ok(!main.includes('MutationObserver'));assert.ok(!main.includes('setInterval('));
assert.ok(modelSource.includes('vetta-driver-intelligence-v3'));assert.ok(store.includes('history.pushState'));assert.ok(store.includes('popstate'));
assert.ok(dashboard.includes('r360NowHero'));assert.ok(planning.includes('Quatro decisões formam seu plano'));assert.ok(planning.includes('Marcar como pago não remove o custo da matemática'));assert.ok(record.includes('Prévia antes de salvar'));assert.ok(results.includes('O que formou este resultado'));assert.ok(more.includes('Tudo que não precisa disputar sua rotina'));assert.ok(onboarding.includes('Como você trabalha hoje?'));
assert.ok(css.includes('@media (min-width:840px)'));assert.ok(css.includes('prefers-reduced-motion'));assert.ok(friendlyCss.includes('prefers-reduced-motion'));
assert.ok(interaction.includes('friendly-week-progress'));assert.ok(interaction.includes('Rascunho salvo · pode sair e voltar'));assert.ok(interaction.includes('friendlyGlobalSearch'));assert.ok(interaction.includes('Continuar meu plano'));assert.ok(interaction.includes('data-friendly-result-date'));assert.ok(interaction.includes('MutationObserver'));
assert.equal(manifest.short_name,'VETTA');assert.equal(manifest.start_url,'./app-shell.html');assert.ok(sw.includes('vetta-premium-ui-2'));assert.ok(sw.includes("'./ui/main.js'"));assert.ok(sw.includes("'./ui/interaction.js'"));assert.ok(sw.includes("'./ui/friendly.css'"));assert.ok(!sw.includes('refactor-360.js'));assert.ok(sw.includes('HAD_ACTIVE_WORKER'));

const memory=new Map();globalThis.localStorage={getItem:key=>memory.has(key)?memory.get(key):null,setItem:(key,value)=>memory.set(key,String(value)),removeItem:key=>memory.delete(key)};
const {VettaModel,STORAGE_KEY}=await import('../ui/model.js');const model=new VettaModel();model.state.onboardingComplete=true;model.state.targetProfit=4000;model.state.costs=[{id:'rent',name:'Aluguel',kind:'monthly',category:'obligation',value:650,active:true,paidPeriods:[]},{id:'fee',name:'Taxa da plataforma',kind:'percent',category:'obligation',value:10,active:true,paidPeriods:[]}];model.save();
const reloadedWithPercent=new VettaModel();assert.equal(reloadedWithPercent.state.costs.some(cost=>cost.id==='fee'),true,'atualização não pode apagar custo percentual existente');assert.equal(reloadedWithPercent.costContext().percent,0.10,'custo percentual preservado deve continuar na matemática');
const before={monthly:reloadedWithPercent.costContext().monthlyFixed,percent:reloadedWithPercent.costContext().percent,projected:reloadedWithPercent.calculations().projectedNet};reloadedWithPercent.setPaid(reloadedWithPercent.state.costs.find(cost=>cost.id==='rent'),true);const paid={monthly:reloadedWithPercent.costContext().monthlyFixed,percent:reloadedWithPercent.costContext().percent,projected:reloadedWithPercent.calculations().projectedNet};assert.deepEqual(paid,before,'marcar pago não pode retirar custo da matemática');
let saved=reloadedWithPercent.saveRecord({date:'2026-08-08',gross:450,km:180,hours:8,fuelSpend:50});assert.equal(saved.ok,true);assert.equal(reloadedWithPercent.state.records.length,1);saved=reloadedWithPercent.saveRecord({date:'2026-08-08',gross:500,km:185,hours:8,fuelSpend:52});assert.equal(saved.updated,true);assert.equal(reloadedWithPercent.state.records.length,1,'mesma data atualiza, não duplica');reloadedWithPercent.state.targetProfit=0;reloadedWithPercent.save();const restored=new VettaModel();assert.equal(restored.state.targetProfit,0);assert.ok(memory.get(STORAGE_KEY));
console.log('Premium UI + friendly UX contract passed');
