import { model, ui, h, weekPresentation, criticalCosts, nextAction } from '../context.js';

const icon = glyph => `<span aria-hidden="true">${glyph}</span>`;

export function renderTopbar() {
  const planning = ui.state.route === 'planning';
  return `<header class="topbar"><div class="topbar-inner"><div class="brand"><div class="brand-mark">V</div><div><strong class="brand-title">VETTA</strong><span class="brand-sub">Driver Intelligence</span></div></div>${planning?'':`<button id="r1HeaderPlanButton" class="top-action" type="button" data-open-plan>Meu plano</button>`}</div></header>`;
}

export function renderNav() {
  const hidden = ui.state.route === 'day' || !model.state.onboardingComplete ? 'hidden' : '';
  const active = ui.state.primary;
  const items = [['dashboard','Agora','⌂'],['history','Resultados','↗'],['day','Registrar','+'],['costs','Custos','▣'],['more','Mais','•••']];
  return `<nav class="nav-shell fixed bottom-0 ${hidden}" data-r1-navigation="ready" data-block1d="ready">${items.map(([view,label,glyph])=>`<button type="button" class="nav-item ${view==='day'?'r360-register-action ':''}${active===view?'active':''}" data-view="${view}" aria-label="${label}">${icon(glyph)}<span>${label}</span></button>`).join('')}</nav>`;
}

export function renderDashboard() {
  const c=model.calculations(), wp=weekPresentation(), action=nextAction(), critical=criticalCosts();
  const monthRemaining=Math.max(0,model.state.targetProfit-c.actualNet), hasWeek=wp.week.records.length>0;
  const heroLabel=!hasWeek?'Sua semana ainda não começou no VETTA':wp.delta>=0?'Sua semana está no ritmo':`Faltam ${model.money(Math.abs(wp.delta),0)} para o ritmo da semana`;
  const planMissing=model.state.targetProfit<=0;
  return `<section id="view-dashboard" class="view-section ${ui.state.route==='dashboard'?'':'hidden'}" data-r1="ready" data-r1-state="${planMissing?'missing-target':'ready'}">
    <div id="r360NowHero" class="hero"><span class="eyebrow">Agora · ${new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'short'}).format(new Date())}</span><strong class="hero-value">${h(heroLabel)}</strong><p class="hero-note">${hasWeek?`${model.money(wp.week.actual,0)} líquidos nesta semana de ${model.money(wp.week.target,0)} planejados.`:'Registre o primeiro dia para transformar o plano em acompanhamento real.'}</p><div class="hero-metrics"><div class="hero-metric"><small>Mês</small><strong>${model.money(c.actualNet,0)}</strong><small>${monthRemaining?`${model.money(monthRemaining,0)} ainda faltam`:'meta líquida alcançada'}</small></div><div class="hero-metric"><small>Projeção</small><strong>${model.money(c.projectedNet,0)}</strong><small>com os dados atuais</small></div></div></div>
    <button id="r1NextAction" class="surface next-action full section-gap" type="button" data-next-action="${action.mode}"><span id="r1NextActionIconWrap" class="next-icon"><span id="r1NextActionIcon">${action.glyph}</span></span><span class="next-copy"><strong id="r1NextActionTitle">${h(action.title)}</strong><p id="r1NextActionText">${h(action.text)}</p></span><span id="r1NextActionButton" class="next-arrow" aria-hidden="true">›</span></button>
    <button id="r360WeekSummary" class="surface full section-gap" type="button" data-open-results="week"><div style="display:flex;justify-content:space-between;align-items:flex-end"><div><span class="eyebrow">Resumo semanal</span><strong class="section-title">${h(wp.title)}</strong></div><span id="weekStatusPill" class="pill ${wp.delta>=0&&hasWeek?'good':hasWeek?'warn':''}">${wp.pill}</span></div><p id="weekStatusText" class="copy">${h(wp.text)}</p><span id="weekStatusTitle" hidden>${h(wp.title)}</span><div class="metric-grid section-gap"><div class="metric"><small>Meta líquida</small><strong id="weekTarget">${model.money(wp.week.target,0)}</strong></div><div class="metric"><small>Realizado</small><strong id="weekActual">${model.money(wp.week.actual,0)}</strong></div><div class="metric"><small>Falta</small><strong>${model.money(Math.max(0,wp.week.target-wp.week.actual),0)}</strong></div><div class="metric"><small>Média/km</small><strong id="weekRevenueKm">${model.money(wp.week.revenueKm)}</strong></div></div></button>
    <div class="card-vetta plan-card section-gap"><div class="plan-main"><span class="eyebrow">Plano do mês</span><strong id="targetProfitDisplay" class="plan-value">${planMissing?'Sem meta':model.money(model.state.targetProfit,0)}</strong><div id="r1PlanSummary" class="plan-meta">${planMissing?'Defina quanto precisa sobrar.':`${c.ctx.plannedDays} dias planejados · ${model.money(c.dailyNet,0)}/dia líquido`}</div><span id="r1PlanStatus" class="pill ${planMissing?'warn':'blue'}" style="margin-top:10px">${planMissing?'FALTA META':'PLANO ATIVO'}</span></div><button id="r1PlanButton" type="button" class="secondary" data-open-plan>${planMissing?'Montar meu plano':'Revisar plano'}</button></div>
    <section id="r360FinancialAttention" class="section-gap">${critical.length?`<div class="attention"><strong>${critical.length===1?'Há uma obrigação que pede ação agora':`Há ${critical.length} obrigações que pedem ação agora`}</strong>${critical.slice(0,2).map(item=>`<button type="button" class="row" data-open-costs><span class="row-copy"><strong>${h(item.cost.name)}</strong><small>${h(item.meta.label)} · ${h(model.costCadence(item.cost))}</small></span><span class="chev">›</span></button>`).join('')}</div>`:`<div class="positive"><strong>Sem atenção financeira crítica agora</strong><small>Contas, reservas e custos continuam organizados em Custos.</small></div>`}</section>
    <section class="surface section-gap"><span class="eyebrow">Leitura VETTA</span><strong class="section-title">${c.records.length?(c.paceDelta>=0?'Seu ritmo está saudável':'Seu mês pede recuperação'):'Seu plano está pronto para começar'}</strong><p class="copy">${c.records.length?(c.paceDelta>=0?`A projeção atual é ${model.money(c.projectedNet,0)} líquidos.`:`O ritmo acumulado está ${model.money(Math.abs(c.paceDelta),0)} abaixo do planejado.`):`Com ${model.state.fuel.label}, o custo estimado de combustível está em ${model.money(c.fuelKm)}/km.`}</p></section>
    <button data-view="day" class="hidden">Registrar meu dia</button><div class="hidden"><div><h3 id="monthStatusTitle">Situação do mês</h3></div></div><canvas id="revenueChart" hidden></canvas><button id="installButton" hidden></button>
  </section>`;
}
